alphabot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  Rev18_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 18
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  Rev19_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 19
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  Rev30_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 30
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  Rev31_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 31
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  # Effort Controllers
  leftWheel_effor_controller:
    type: effort_controllers/JointEffortController
    joint: Revolute 18
    pid: { p: 100.0, i: 0.1, d: 10.0 }

  rightWheel_effor_controller:
    type: effort_controllers/JointEffortController
    joint: Revolute 19
    pid: { p: 100.0, i: 0.1, d: 10.0 }
