alphabot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 30
    pid: { p: 7, i: 0.001, d: 0.001 }
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 31
    pid: { p: 7, i: 0.001, d: 0.001 }
